name: Version Bump

on:
  push:
    branches:
      - main

env:
  GH_TOKEN: ${{ secrets.GH_PAT }}

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ env.GH_TOKEN }}
        fetch-depth: 0  # Important for fetching all tags

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Bump2Version
      run: pip install bump2version

    - name: Configure Git User
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git config push.default current

    - name: Extract old version
      run: |
        OLD_VERSION=$(bump2version --dry-run --list patch | grep current_version | sed -r s,"^.*=",,)
        echo "OLD_VERSION=$OLD_VERSION" >> $GITHUB_ENV

    - name: Bump the version
      run: bump2version patch  # Adjust 'patch', 'minor', or 'major' based on your preference

    - name: Extract new version
      run: |
        NEW_VERSION=$(bump2version --dry-run --list patch | grep current_version | sed -r s,"^.*=",,)
        echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

    - name: Create new branch for version bump
      run: |
        BRANCH_NAME="version-$OLD_VERSION-to-$NEW_VERSION"
        git checkout -b $BRANCH_NAME
        echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

    - name: Push changes with verbose logging
      run: git push --
