name: Bump Version and Publish to PyPI

on:
  pull_request:
    branches:
      - main
    types:
      - closed

env:
  GH_TOKEN: ${{ secrets.GH_PAT }}

jobs:
  version-bump-and-publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install bump2version
      run: pip install bump2version

    - name: Bump version and push tag
      run: |
        git config user.email "action@github.com"
        git config user.name "GitHub Action"
        git checkout main  # Ensure we're on the main branch
        bump2version patch  # or 'minor' or 'major', based on your preference
        git push "https://${{ env.GH_TOKEN }}@github.com/${{ github.repository }}" main
        git push "https://${{ env.GH_TOKEN }}@github.com/${{ github.repository }}" --tags

    - name: Build and publish to PyPI
      if: startsWith(github.ref, 'refs/tags')
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        pip install twine wheel
        python setup.py sdist bdist_wheel
        twine upload dist/*
