name: Version Bump and PyPi Publish

on:
  push:
    branches:
      - main

env:
  GH_TOKEN: ${{ secrets.GH_PAT }}

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ env.GH_TOKEN }}
        fetch-depth: 0  # Important for fetching all tags

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Bump2Version
      run: pip install bump2version

    - name: Bump version and create pull request
      run: |
        NEW_BRANCH="version-bump-$(date +'%Y%m%d%H%M%S')"
        git checkout -b $NEW_BRANCH
        bump2version patch  # Adjust 'patch', 'minor', or 'major' based on your preference
        git push origin $NEW_BRANCH

        # Create PR
        PR_EXISTS=$(gh pr list --base main --head $NEW_BRANCH | wc -l)
        if [ "$PR_EXISTS" -eq "0" ]; then
          gh pr create --title "Version Bump" --body "Automated version bump after merge to main." --head $NEW_BRANCH --base main
        fi