name: Package Test

on: [push, pull_request]

jobs:
  test-package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set dummy OpenAI API Key
      run: export OPENAI_API_KEY=dummy_token
      
    - name: Install dependencies
      run: |
        pip install .

    - name: Test package with bash script
      run: ./.github/scripts/test-package.sh