name: Run pytest

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11] # Default version for all branches

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
  
      - name: Set dummy OpenAI API key
        run: echo "OPENAI_API_KEY=dummy_key" >> $GITHUB_ENV
  
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest
  
      - name: Run pytest
        run: pytest
